<template>
  <div class="list" :class="{ 'vertical-align': !isMaxHeightExceeded }">
    <AddressCard
      v-for="(address, index) in addresses"
      ref="address"
      :key="index"
      class="item"
      :used="address.used"
      :selected="selected === index"
      :data-test="`address-${index}`"
      @click="() => selectAddress(index)"
    />
    <AddressCardButton
      data-test="generate-address"
      @click="$emit('generate-address')"
    />
  </div>
</template>

<script>
import AddressCard from '@/components/AddressCard'
import AddressCardButton from '@/components/AddressCardButton'

/**
 * List of all the addresses generated by the wallet
 */
export default {
  name: 'AddressList',
  components: {
    AddressCard,
    AddressCardButton,
  },
  props: {
    /**
     * Addresses generated
     */
    addresses: {
      type: Array,
      required: true,
    },
    /**
     * Address selected
     */
    selected: {
      type: Number,
      default: null,
    },
  },
  computed: {
    isMaxHeightExceeded() {
      // FIXME: calculate a the height in a more agnostic way
      return this.addresses.length > 26
    },
  },
  methods: {
    selectAddress(index) {
      /**
       * Emit the index of the new selected address
       */
      this.$emit('select-address', index)
    },
  },
}
</script>

<style lang="scss" scoped>
@import '@/styles/_colors.scss';
@import '@/styles/scroll.scss';

.list {
  align-items: center;
  background-color: $orange-1;
  border-bottom: 1px solid $grey-1;
  box-sizing: border-box;
  display: grid;
  gap: 6px;
  grid-template-columns: repeat(auto-fit, 25px);
  grid-template-rows: repeat(auto-fit, 40px);
  height: 170px;
  justify-content: center;
  max-height: 170px;
  overflow: auto;
  padding: 25px;

  &.vertical-align {
    align-content: center;
  }
}
</style>

<docs>
### Example

```jsx
  <AddressList
    :style="{ width: '350px' }"
    :addresses="[ {
      pkh: 'twit1270yg7pkm2w9mlq56r0mzrwph3flrp862zw0ft',
      index: 0,
      used: false,
      amount: 5000,
      currency: 'nanoWits',
      firstPaymentDate: new Date(),
      lastPaymentDate: new Date(),
      payments: 0,
    },
    {
      pkh: 'twit1270yg7pkm2w9mlq56r0mzrwph3flrp862zw0fa',
      index: 0,
      used: false,
      amount: 5000,
      currency: 'nanoWits',
      firstPaymentDate: new Date(),
      lastPaymentDate: new Date(),
      payments: 1,
    }]"
  />
```
</docs>
