export const IPC_ACTIONS = {
  Window: {
    SET_MESSAGE: 'SET_MESSAGE',
    SHUTDOWN: 'SHUTDOWN',
    SET_RUNNING_STATUS: 'SET_RUNNING_STATUS',
    SET_DOWNLOADED_STATUS: 'SET_DOWNLOADED_STATUS',
    SET_DOWNLOADING_STATUS: 'SET_DOWNLOADING_STATUS',
    SET_LOADED_STATUS: 'SET_LOADED_STATUS',
    SET_DOWNLOAD_PROGRESS: 'SET_DOWNLOAD_PROGRESS',
    SET_OS_NOT_SUPPORTED: 'SET_OS_NOT_SUPPORTED',
  },
}
