import Vue from 'vue'
import { library } from '@fortawesome/fontawesome-svg-core'
import {
  faAngleLeft,
  faAngleRight,
  faAngleUp,
  faCheck,
  faCheckCircle,
  faCircle,
  faCloudUploadAlt,
  faCode,
  faCoffee,
  faCog,
  faCopy,
  faEdit,
  faEye,
  faFile,
  faFileAlt,
  faFileDownload,
  faFileImport,
  faFileSignature,
  faFileUpload,
  faInfoCircle,
  faLink,
  faLongArrowAltRight,
  faPlus,
  faShoppingBag,
  faSortDown,
  faSortUp,
  faTimes,
  faTimesCircle,
  faTrash,
  faUsers,
  faWallet,
} from '@fortawesome/free-solid-svg-icons'
import { FontAwesomeIcon } from '@fortawesome/vue-fontawesome'

library.add(
  faAngleLeft,
  faAngleRight,
  faAngleUp,
  faCheck,
  faCheckCircle,
  faCircle,
  faCloudUploadAlt,
  faCode,
  faCoffee,
  faCog,
  faCopy,
  faEdit,
  faEye,
  faFile,
  faFileAlt,
  faFileDownload,
  faFileImport,
  faFileSignature,
  faFileUpload,
  faInfoCircle,
  faLink,
  faLongArrowAltRight,
  faPlus,
  faShoppingBag,
  faSortDown,
  faSortUp,
  faTimes,
  faTimesCircle,
  faTrash,
  faUsers,
  faWallet
)
Vue.component('font-awesome-icon', FontAwesomeIcon)
