export const dr = {
  data_request: {
    aggregate: {
      script: [
        {
          hierarchical_type: 'operator',
          markup_type: 'select',
          options: [
            {
              hierarchical_type: 'operator_option',
              label: 'asBytes',
              markup: 'option',
              output_type: 'Bytes',
            },
            {
              hierarchical_type: 'operator_option',
              label: 'count',
              markup: 'option',
              output_type: 'Integer',
            },
            {
              hierarchical_type: 'operator_option',
              label: 'every',
              markup: 'option',
              output_type: 'Boolean',
            },
            {
              hierarchical_type: 'operator_option',
              label: 'filter',
              markup: 'option',
              output_type: 'Array',
            },
            {
              hierarchical_type: 'operator_option',
              label: 'flatten',
              markup: 'option',
              output_type: 'Array',
            },
            {
              hierarchical_type: 'operator_option',
              label: 'get',
              markup: 'option',
              output_type: 'Inner',
            },
            {
              hierarchical_type: 'operator_option',
              label: 'map',
              markup: 'option',
              output_type: 'Argument',
            },
            {
              hierarchical_type: 'operator_option',
              label: 'reduce',
              markup: 'option',
              output_type: 'Inner',
            },
            {
              hierarchical_type: 'operator_option',
              label: 'some',
              markup: 'option',
              output_type: 'Boolean',
            },
            {
              hierarchical_type: 'operator_option',
              label: 'sort',
              markup: 'option',
              output_type: 'Array',
            },
            {
              hierarchical_type: 'operator_option',
              label: 'take',
              markup: 'option',
              output_type: 'Array',
            },
          ],
          output_type: ['Array', 'Passthrough'],
          selected: {
            arguments: [
              {
                hierarchical_type: 'argument',
                id: 7,
                label: 'depth',
                markup_type: 'input',
                value: undefined,
              },
            ],
            hierarchical_type: 'operator_option',
            label: 'flatten',
            output_type: 'bytes',
          },
        },
        {
          hierarchical_type: 'operator',
          markup_type: 'select',
          options: [
            {
              hierarchical_type: 'operator_option',
              label: 'asBytes',
              markup: 'option',
              output_type: 'Bytes',
            },
            {
              hierarchical_type: 'operator_option',
              label: 'count',
              markup: 'option',
              output_type: 'Integer',
            },
            {
              hierarchical_type: 'operator_option',
              label: 'every',
              markup: 'option',
              output_type: 'Boolean',
            },
            {
              hierarchical_type: 'operator_option',
              label: 'filter',
              markup: 'option',
              output_type: 'Array',
            },
            {
              hierarchical_type: 'operator_option',
              label: 'flatten',
              markup: 'option',
              output_type: 'Array',
            },
            {
              hierarchical_type: 'operator_option',
              label: 'get',
              markup: 'option',
              output_type: 'Inner',
            },
            {
              hierarchical_type: 'operator_option',
              label: 'map',
              markup: 'option',
              output_type: 'Argument',
            },
            {
              hierarchical_type: 'operator_option',
              label: 'reduce',
              markup: 'option',
              output_type: 'Inner',
            },
            {
              hierarchical_type: 'operator_option',
              label: 'some',
              markup: 'option',
              output_type: 'Boolean',
            },
            {
              hierarchical_type: 'operator_option',
              label: 'sort',
              markup: 'option',
              output_type: 'Array',
            },
            {
              hierarchical_type: 'operator_option',
              label: 'take',
              markup: 'option',
              output_type: 'Array',
            },
          ],
          output_type: ['Array', 'Inner'],
          selected: {
            arguments: [
              {
                hierarchical_type: 'argument',
                id: 8,
                label: 'function',
                markup_type: 'input',
                options: [
                  {
                    hierarchical_type: 'argument_option',
                    label: 'greaterThan',
                    markup_type: 'option',
                    meta: {},
                    output_type: 'Bytes',
                  },
                  {
                    hierarchical_type: 'argument_option',
                    label: 'lessThan',
                    markup_type: 'option',
                    meta: {},
                    output_type: 'Bytes',
                  },
                  {
                    hierarchical_type: 'argument_option',
                    label: 'equals',
                    markup_type: 'option',
                    meta: {},
                    output_type: 'Bytes',
                  },
                  {
                    hierarchical_type: 'argument_option',
                    label: 'deviationAbsolute',
                    markup_type: 'option',
                    meta: {},
                    output_type: 'Bytes',
                  },
                  {
                    hierarchical_type: 'argument_option',
                    label: 'deviationRelative',
                    markup_type: 'option',
                    meta: {},
                    output_type: 'Bytes',
                  },
                  {
                    hierarchical_type: 'argument_option',
                    label: 'deviationStandard',
                    markup_type: 'option',
                    meta: {},
                    output_type: 'Bytes',
                  },
                  {
                    hierarchical_type: 'argument_option',
                    label: 'top',
                    markup_type: 'option',
                    meta: {},
                    output_type: 'Bytes',
                  },
                  {
                    hierarchical_type: 'argument_option',
                    label: 'bottom',
                    markup_type: 'option',
                    meta: {},
                    output_type: 'Bytes',
                  },
                  {
                    hierarchical_type: 'argument_option',
                    label: 'lessOrEqualThan',
                    markup_type: 'option',
                    meta: {},
                    output_type: 'Bytes',
                  },
                  {
                    hierarchical_type: 'argument_option',
                    label: 'greaterOrEqualThan',
                    markup_type: 'option',
                    meta: {},
                    output_type: 'Bytes',
                  },
                  {
                    hierarchical_type: 'argument_option',
                    label: 'notEquals',
                    markup_type: 'option',
                    meta: {},
                    output_type: 'Bytes',
                  },
                  {
                    hierarchical_type: 'argument_option',
                    label: 'notDeviationAbsolute',
                    markup_type: 'option',
                    meta: {},
                    output_type: 'Bytes',
                  },
                  {
                    hierarchical_type: 'argument_option',
                    label: 'notDeviationRelative',
                    markup_type: 'option',
                    meta: {},
                    output_type: 'Bytes',
                  },
                  {
                    hierarchical_type: 'argument_option',
                    label: 'notDeviationStandard',
                    markup_type: 'option',
                    meta: {},
                    output_type: 'Bytes',
                  },
                  {
                    hierarchical_type: 'argument_option',
                    label: 'notTop',
                    markup_type: 'option',
                    meta: {},
                    output_type: 'Bytes',
                  },
                  {
                    hierarchical_type: 'argument_option',
                    label: 'notBottom',
                    markup_type: 'option',
                    meta: {},
                    output_type: 'Bytes',
                  },
                ],
                selected: {
                  hierarchical_type: 'operator_option',
                  label: 'deviationStandard',
                  markup_type: 'option',
                  output_type: 'array',
                },
              },
            ],
            hierarchical_type: 'operator_option',
            label: 'filter',
            output_type: 'bytes',
          },
        },
        {
          hierarchical_type: 'operator',
          markup_type: 'select',
          options: [
            {
              hierarchical_type: 'operator_option',
              label: 'asBytes',
              markup: 'option',
              output_type: 'Bytes',
            },
            {
              hierarchical_type: 'operator_option',
              label: 'count',
              markup: 'option',
              output_type: 'Integer',
            },
            {
              hierarchical_type: 'operator_option',
              label: 'every',
              markup: 'option',
              output_type: 'Boolean',
            },
            {
              hierarchical_type: 'operator_option',
              label: 'filter',
              markup: 'option',
              output_type: 'Array',
            },
            {
              hierarchical_type: 'operator_option',
              label: 'flatten',
              markup: 'option',
              output_type: 'Array',
            },
            {
              hierarchical_type: 'operator_option',
              label: 'get',
              markup: 'option',
              output_type: 'Inner',
            },
            {
              hierarchical_type: 'operator_option',
              label: 'map',
              markup: 'option',
              output_type: 'Argument',
            },
            {
              hierarchical_type: 'operator_option',
              label: 'reduce',
              markup: 'option',
              output_type: 'Inner',
            },
            {
              hierarchical_type: 'operator_option',
              label: 'some',
              markup: 'option',
              output_type: 'Boolean',
            },
            {
              hierarchical_type: 'operator_option',
              label: 'sort',
              markup: 'option',
              output_type: 'Array',
            },
            {
              hierarchical_type: 'operator_option',
              label: 'take',
              markup: 'option',
              output_type: 'Array',
            },
          ],
          output_type: ['Inner'],
          selected: {
            arguments: [
              {
                hierarchical_type: 'argument',
                id: 9,
                label: 'function',
                markup_type: 'input',
                options: [
                  {
                    hierarchical_type: 'argument_option',
                    label: 'min',
                    markup_type: 'option',
                    meta: {},
                    output_type: 'integer',
                  },
                  {
                    hierarchical_type: 'argument_option',
                    label: 'max',
                    markup_type: 'option',
                    meta: {},
                    output_type: 'integer',
                  },
                  {
                    hierarchical_type: 'argument_option',
                    label: 'averageMean',
                    markup_type: 'option',
                    meta: {},
                    output_type: 'integer',
                  },
                  {
                    hierarchical_type: 'argument_option',
                    label: 'max',
                    markup_type: 'option',
                    meta: {},
                    output_type: 'integer',
                  },
                  {
                    hierarchical_type: 'argument_option',
                    label: 'averageMean',
                    markup_type: 'option',
                    meta: {},
                    output_type: 'integer',
                  },
                  {
                    hierarchical_type: 'argument_option',
                    label: 'averageMeanWeighted',
                    markup_type: 'option',
                    meta: {},
                    output_type: 'integer',
                  },
                  {
                    hierarchical_type: 'argument_option',
                    label: 'averageMedian',
                    markup_type: 'option',
                    meta: {},
                    output_type: 'integer',
                  },
                  {
                    hierarchical_type: 'argument_option',
                    label: 'averageMedianWeighted',
                    markup_type: 'option',
                    meta: {},
                    output_type: 'integer',
                  },
                  {
                    hierarchical_type: 'argument_option',
                    label: 'deviationStandard',
                    markup_type: 'option',
                    meta: {},
                    output_type: 'integer',
                  },
                  {
                    hierarchical_type: 'argument_option',
                    label: 'deviationAverage',
                    markup_type: 'option',
                    meta: {},
                    output_type: 'integer',
                  },
                  {
                    hierarchical_type: 'argument_option',
                    label: 'deviationMedian',
                    markup_type: 'option',
                    meta: {},
                    output_type: 'integer',
                  },
                  {
                    hierarchical_type: 'argument_option',
                    label: 'deviationMaximum',
                    markup_type: 'option',
                    meta: {},
                    output_type: 'integer',
                  },
                ],
                selected: {
                  hierarchical_type: 'operator_option',
                  label: 'averageMean',
                  markup_type: 'option',
                  output_type: 'array',
                },
              },
            ],
            hierarchical_type: 'operator_option',
            label: 'reduce',
            output_type: 'bytes',
          },
        },
      ],
    },
    notBefore: 1669852800,
    retrieve: [
      {
        script: [
          {
            hierarchical_type: 'operator',
            markup_type: 'select',
            options: [
              {
                hierarchical_type: 'operator_option',
                label: 'asArray',
                markup: 'option',
                output_type: 'Array',
              },
              {
                hierarchical_type: 'operator_option',
                label: 'asBoolean',
                markup: 'option',
                output_type: 'Boolean',
              },
              {
                hierarchical_type: 'operator_option',
                label: 'asFloat',
                markup: 'option',
                output_type: 'Float',
              },
              {
                hierarchical_type: 'operator_option',
                label: 'asInteger',
                markup: 'option',
                output_type: 'Integer',
              },
              {
                hierarchical_type: 'operator_option',
                label: 'asMap',
                markup: 'option',
                output_type: 'Map',
              },
              {
                hierarchical_type: 'operator_option',
                label: 'asString',
                markup: 'option',
                output_type: 'String',
              },
              {
                hierarchical_type: 'operator_option',
                label: 'hash',
                markup: 'option',
                output_type: 'Bytes',
              },
            ],
            output_type: ['String'],
            selected: {
              arguments: [],
              hierarchical_type: 'operator_option',
              label: 'asString',
              output_type: 'bytes',
            },
          },
          {
            hierarchical_type: 'operator',
            markup_type: 'select',
            options: [
              {
                hierarchical_type: 'operator_option',
                label: 'asBytes',
                markup: 'option',
                output_type: 'Bytes',
              },
              {
                hierarchical_type: 'operator_option',
                label: 'asFloat',
                markup: 'option',
                output_type: 'Float',
              },
              {
                hierarchical_type: 'operator_option',
                label: 'asInteger',
                markup: 'option',
                output_type: 'Integer',
              },
              {
                hierarchical_type: 'operator_option',
                label: 'length',
                markup: 'option',
                output_type: 'Integer',
              },
              {
                hierarchical_type: 'operator_option',
                label: 'match',
                markup: 'option',
                output_type: 'Argument',
              },
              {
                hierarchical_type: 'operator_option',
                label: 'parseJSON',
                markup: 'option',
                output_type: 'Bytes',
              },
              {
                hierarchical_type: 'operator_option',
                label: 'parseXML',
                markup: 'option',
                output_type: 'Map',
              },
              {
                hierarchical_type: 'operator_option',
                label: 'asBoolean',
                markup: 'option',
                output_type: 'Boolean',
              },
              {
                hierarchical_type: 'operator_option',
                label: 'toLowerCase',
                markup: 'option',
                output_type: 'String',
              },
              {
                hierarchical_type: 'operator_option',
                label: 'toUpperCase',
                markup: 'option',
                output_type: 'String',
              },
            ],
            output_type: ['Bytes'],
            selected: {
              arguments: [],
              hierarchical_type: 'operator_option',
              label: 'parseJson',
              output_type: 'bytes',
            },
          },
          {
            hierarchical_type: 'operator',
            markup_type: 'select',
            options: [
              {
                hierarchical_type: 'operator_option',
                label: 'asArray',
                markup: 'option',
                output_type: 'Array',
              },
              {
                hierarchical_type: 'operator_option',
                label: 'asBoolean',
                markup: 'option',
                output_type: 'Boolean',
              },
              {
                hierarchical_type: 'operator_option',
                label: 'asFloat',
                markup: 'option',
                output_type: 'Float',
              },
              {
                hierarchical_type: 'operator_option',
                label: 'asInteger',
                markup: 'option',
                output_type: 'Integer',
              },
              {
                hierarchical_type: 'operator_option',
                label: 'asMap',
                markup: 'option',
                output_type: 'Map',
              },
              {
                hierarchical_type: 'operator_option',
                label: 'asString',
                markup: 'option',
                output_type: 'String',
              },
              {
                hierarchical_type: 'operator_option',
                label: 'hash',
                markup: 'option',
                output_type: 'Bytes',
              },
            ],
            output_type: ['Map', 'Bytes'],
            selected: {
              arguments: [],
              hierarchical_type: 'operator_option',
              label: 'asMap',
              output_type: 'bytes',
            },
          },
          {
            hierarchical_type: 'operator',
            markup_type: 'select',
            options: [
              {
                hierarchical_type: 'operator_option',
                label: 'entries',
                markup: 'option',
                output_type: 'Array',
              },
              {
                hierarchical_type: 'operator_option',
                label: 'get',
                markup: 'option',
                output_type: 'Inner',
              },
              {
                hierarchical_type: 'operator_option',
                label: 'keys',
                markup: 'option',
                output_type: 'String',
              },
              {
                hierarchical_type: 'operator_option',
                label: 'values',
                markup: 'option',
                output_type: 'Inner',
              },
            ],
            output_type: ['Inner'],
            selected: {
              arguments: [
                {
                  hierarchical_type: 'argument',
                  id: 1,
                  label: 'key',
                  markup_type: 'input',
                  value: 'bpi',
                },
              ],
              hierarchical_type: 'operator_option',
              label: 'get',
              output_type: 'bytes',
            },
          },
          {
            hierarchical_type: 'operator',
            markup_type: 'select',
            options: [
              {
                hierarchical_type: 'operator_option',
                label: 'asArray',
                markup: 'option',
                output_type: 'Array',
              },
              {
                hierarchical_type: 'operator_option',
                label: 'asBoolean',
                markup: 'option',
                output_type: 'Boolean',
              },
              {
                hierarchical_type: 'operator_option',
                label: 'asFloat',
                markup: 'option',
                output_type: 'Float',
              },
              {
                hierarchical_type: 'operator_option',
                label: 'asInteger',
                markup: 'option',
                output_type: 'Integer',
              },
              {
                hierarchical_type: 'operator_option',
                label: 'asMap',
                markup: 'option',
                output_type: 'Map',
              },
              {
                hierarchical_type: 'operator_option',
                label: 'asString',
                markup: 'option',
                output_type: 'String',
              },
              {
                hierarchical_type: 'operator_option',
                label: 'hash',
                markup: 'option',
                output_type: 'Bytes',
              },
            ],
            output_type: ['Map', 'Bytes'],
            selected: {
              arguments: [],
              hierarchical_type: 'operator_option',
              label: 'asMap',
              output_type: 'bytes',
            },
          },
          {
            hierarchical_type: 'operator',
            markup_type: 'select',
            options: [
              {
                hierarchical_type: 'operator_option',
                label: 'entries',
                markup: 'option',
                output_type: 'Array',
              },
              {
                hierarchical_type: 'operator_option',
                label: 'get',
                markup: 'option',
                output_type: 'Inner',
              },
              {
                hierarchical_type: 'operator_option',
                label: 'keys',
                markup: 'option',
                output_type: 'String',
              },
              {
                hierarchical_type: 'operator_option',
                label: 'values',
                markup: 'option',
                output_type: 'Inner',
              },
            ],
            output_type: ['Inner'],
            selected: {
              arguments: [
                {
                  hierarchical_type: 'argument',
                  id: 2,
                  label: 'key',
                  markup_type: 'input',
                  value: 'USD',
                },
              ],
              hierarchical_type: 'operator_option',
              label: 'get',
              output_type: 'bytes',
            },
          },
          {
            hierarchical_type: 'operator',
            markup_type: 'select',
            options: [
              {
                hierarchical_type: 'operator_option',
                label: 'asArray',
                markup: 'option',
                output_type: 'Array',
              },
              {
                hierarchical_type: 'operator_option',
                label: 'asBoolean',
                markup: 'option',
                output_type: 'Boolean',
              },
              {
                hierarchical_type: 'operator_option',
                label: 'asFloat',
                markup: 'option',
                output_type: 'Float',
              },
              {
                hierarchical_type: 'operator_option',
                label: 'asInteger',
                markup: 'option',
                output_type: 'Integer',
              },
              {
                hierarchical_type: 'operator_option',
                label: 'asMap',
                markup: 'option',
                output_type: 'Map',
              },
              {
                hierarchical_type: 'operator_option',
                label: 'asString',
                markup: 'option',
                output_type: 'String',
              },
              {
                hierarchical_type: 'operator_option',
                label: 'hash',
                markup: 'option',
                output_type: 'Bytes',
              },
            ],
            output_type: ['Map', 'Bytes'],
            selected: {
              arguments: [],
              hierarchical_type: 'operator_option',
              label: 'asMap',
              output_type: 'bytes',
            },
          },
          {
            hierarchical_type: 'operator',
            markup_type: 'select',
            options: [
              {
                hierarchical_type: 'operator_option',
                label: 'entries',
                markup: 'option',
                output_type: 'Array',
              },
              {
                hierarchical_type: 'operator_option',
                label: 'get',
                markup: 'option',
                output_type: 'Inner',
              },
              {
                hierarchical_type: 'operator_option',
                label: 'keys',
                markup: 'option',
                output_type: 'String',
              },
              {
                hierarchical_type: 'operator_option',
                label: 'values',
                markup: 'option',
                output_type: 'Inner',
              },
            ],
            output_type: ['Inner'],
            selected: {
              arguments: [
                {
                  hierarchical_type: 'argument',
                  id: 3,
                  label: 'key',
                  markup_type: 'input',
                  value: 'rate_float',
                },
              ],
              hierarchical_type: 'operator_option',
              label: 'get',
              output_type: 'bytes',
            },
          },
          {
            hierarchical_type: 'operator',
            markup_type: 'select',
            options: [
              {
                hierarchical_type: 'operator_option',
                label: 'asArray',
                markup: 'option',
                output_type: 'Array',
              },
              {
                hierarchical_type: 'operator_option',
                label: 'asBoolean',
                markup: 'option',
                output_type: 'Boolean',
              },
              {
                hierarchical_type: 'operator_option',
                label: 'asFloat',
                markup: 'option',
                output_type: 'Float',
              },
              {
                hierarchical_type: 'operator_option',
                label: 'asInteger',
                markup: 'option',
                output_type: 'Integer',
              },
              {
                hierarchical_type: 'operator_option',
                label: 'asMap',
                markup: 'option',
                output_type: 'Map',
              },
              {
                hierarchical_type: 'operator_option',
                label: 'asString',
                markup: 'option',
                output_type: 'String',
              },
              {
                hierarchical_type: 'operator_option',
                label: 'hash',
                markup: 'option',
                output_type: 'Bytes',
              },
            ],
            output_type: ['Float'],
            selected: {
              arguments: [],
              hierarchical_type: 'operator_option',
              label: 'asFloat',
              output_type: 'bytes',
            },
          },
        ],
        url: 'https://api.coindesk.com/v1/bpi/currentprice.json',
      },
      {
        script: [
          {
            hierarchical_type: 'operator',
            markup_type: 'select',
            options: [
              {
                hierarchical_type: 'operator_option',
                label: 'asArray',
                markup: 'option',
                output_type: 'Array',
              },
              {
                hierarchical_type: 'operator_option',
                label: 'asBoolean',
                markup: 'option',
                output_type: 'Boolean',
              },
              {
                hierarchical_type: 'operator_option',
                label: 'asFloat',
                markup: 'option',
                output_type: 'Float',
              },
              {
                hierarchical_type: 'operator_option',
                label: 'asInteger',
                markup: 'option',
                output_type: 'Integer',
              },
              {
                hierarchical_type: 'operator_option',
                label: 'asMap',
                markup: 'option',
                output_type: 'Map',
              },
              {
                hierarchical_type: 'operator_option',
                label: 'asString',
                markup: 'option',
                output_type: 'String',
              },
              {
                hierarchical_type: 'operator_option',
                label: 'hash',
                markup: 'option',
                output_type: 'Bytes',
              },
            ],
            output_type: ['String'],
            selected: {
              arguments: [],
              hierarchical_type: 'operator_option',
              label: 'asString',
              output_type: 'bytes',
            },
          },
          {
            hierarchical_type: 'operator',
            markup_type: 'select',
            options: [
              {
                hierarchical_type: 'operator_option',
                label: 'asBytes',
                markup: 'option',
                output_type: 'Bytes',
              },
              {
                hierarchical_type: 'operator_option',
                label: 'asFloat',
                markup: 'option',
                output_type: 'Float',
              },
              {
                hierarchical_type: 'operator_option',
                label: 'asInteger',
                markup: 'option',
                output_type: 'Integer',
              },
              {
                hierarchical_type: 'operator_option',
                label: 'length',
                markup: 'option',
                output_type: 'Integer',
              },
              {
                hierarchical_type: 'operator_option',
                label: 'match',
                markup: 'option',
                output_type: 'Argument',
              },
              {
                hierarchical_type: 'operator_option',
                label: 'parseJSON',
                markup: 'option',
                output_type: 'Bytes',
              },
              {
                hierarchical_type: 'operator_option',
                label: 'parseXML',
                markup: 'option',
                output_type: 'Map',
              },
              {
                hierarchical_type: 'operator_option',
                label: 'asBoolean',
                markup: 'option',
                output_type: 'Boolean',
              },
              {
                hierarchical_type: 'operator_option',
                label: 'toLowerCase',
                markup: 'option',
                output_type: 'String',
              },
              {
                hierarchical_type: 'operator_option',
                label: 'toUpperCase',
                markup: 'option',
                output_type: 'String',
              },
            ],
            output_type: ['Bytes'],
            selected: {
              arguments: [],
              hierarchical_type: 'operator_option',
              label: 'parseJson',
              output_type: 'bytes',
            },
          },
          {
            hierarchical_type: 'operator',
            markup_type: 'select',
            options: [
              {
                hierarchical_type: 'operator_option',
                label: 'asArray',
                markup: 'option',
                output_type: 'Array',
              },
              {
                hierarchical_type: 'operator_option',
                label: 'asBoolean',
                markup: 'option',
                output_type: 'Boolean',
              },
              {
                hierarchical_type: 'operator_option',
                label: 'asFloat',
                markup: 'option',
                output_type: 'Float',
              },
              {
                hierarchical_type: 'operator_option',
                label: 'asInteger',
                markup: 'option',
                output_type: 'Integer',
              },
              {
                hierarchical_type: 'operator_option',
                label: 'asMap',
                markup: 'option',
                output_type: 'Map',
              },
              {
                hierarchical_type: 'operator_option',
                label: 'asString',
                markup: 'option',
                output_type: 'String',
              },
              {
                hierarchical_type: 'operator_option',
                label: 'hash',
                markup: 'option',
                output_type: 'Bytes',
              },
            ],
            output_type: ['Map', 'Bytes'],
            selected: {
              arguments: [],
              hierarchical_type: 'operator_option',
              label: 'asMap',
              output_type: 'bytes',
            },
          },
          {
            hierarchical_type: 'operator',
            markup_type: 'select',
            options: [
              {
                hierarchical_type: 'operator_option',
                label: 'entries',
                markup: 'option',
                output_type: 'Array',
              },
              {
                hierarchical_type: 'operator_option',
                label: 'get',
                markup: 'option',
                output_type: 'Inner',
              },
              {
                hierarchical_type: 'operator_option',
                label: 'keys',
                markup: 'option',
                output_type: 'String',
              },
              {
                hierarchical_type: 'operator_option',
                label: 'values',
                markup: 'option',
                output_type: 'Inner',
              },
            ],
            output_type: ['Inner'],
            selected: {
              arguments: [
                {
                  hierarchical_type: 'argument',
                  id: 4,
                  label: 'key',
                  markup_type: 'input',
                  value: 'USD',
                },
              ],
              hierarchical_type: 'operator_option',
              label: 'get',
              output_type: 'bytes',
            },
          },
          {
            hierarchical_type: 'operator',
            markup_type: 'select',
            options: [
              {
                hierarchical_type: 'operator_option',
                label: 'asArray',
                markup: 'option',
                output_type: 'Array',
              },
              {
                hierarchical_type: 'operator_option',
                label: 'asBoolean',
                markup: 'option',
                output_type: 'Boolean',
              },
              {
                hierarchical_type: 'operator_option',
                label: 'asFloat',
                markup: 'option',
                output_type: 'Float',
              },
              {
                hierarchical_type: 'operator_option',
                label: 'asInteger',
                markup: 'option',
                output_type: 'Integer',
              },
              {
                hierarchical_type: 'operator_option',
                label: 'asMap',
                markup: 'option',
                output_type: 'Map',
              },
              {
                hierarchical_type: 'operator_option',
                label: 'asString',
                markup: 'option',
                output_type: 'String',
              },
              {
                hierarchical_type: 'operator_option',
                label: 'hash',
                markup: 'option',
                output_type: 'Bytes',
              },
            ],
            output_type: ['Map', 'Bytes'],
            selected: {
              arguments: [],
              hierarchical_type: 'operator_option',
              label: 'asMap',
              output_type: 'bytes',
            },
          },
          {
            hierarchical_type: 'operator',
            markup_type: 'select',
            options: [
              {
                hierarchical_type: 'operator_option',
                label: 'entries',
                markup: 'option',
                output_type: 'Array',
              },
              {
                hierarchical_type: 'operator_option',
                label: 'get',
                markup: 'option',
                output_type: 'Inner',
              },
              {
                hierarchical_type: 'operator_option',
                label: 'keys',
                markup: 'option',
                output_type: 'String',
              },
              {
                hierarchical_type: 'operator_option',
                label: 'values',
                markup: 'option',
                output_type: 'Inner',
              },
            ],
            output_type: ['Inner'],
            selected: {
              arguments: [
                {
                  hierarchical_type: 'argument',
                  id: 5,
                  label: 'key',
                  markup_type: 'input',
                  value: '15m',
                },
              ],
              hierarchical_type: 'operator_option',
              label: 'get',
              output_type: 'bytes',
            },
          },
          {
            hierarchical_type: 'operator',
            markup_type: 'select',
            options: [
              {
                hierarchical_type: 'operator_option',
                label: 'asArray',
                markup: 'option',
                output_type: 'Array',
              },
              {
                hierarchical_type: 'operator_option',
                label: 'asBoolean',
                markup: 'option',
                output_type: 'Boolean',
              },
              {
                hierarchical_type: 'operator_option',
                label: 'asFloat',
                markup: 'option',
                output_type: 'Float',
              },
              {
                hierarchical_type: 'operator_option',
                label: 'asInteger',
                markup: 'option',
                output_type: 'Integer',
              },
              {
                hierarchical_type: 'operator_option',
                label: 'asMap',
                markup: 'option',
                output_type: 'Map',
              },
              {
                hierarchical_type: 'operator_option',
                label: 'asString',
                markup: 'option',
                output_type: 'String',
              },
              {
                hierarchical_type: 'operator_option',
                label: 'hash',
                markup: 'option',
                output_type: 'Bytes',
              },
            ],
            output_type: ['Float'],
            selected: {
              arguments: [],
              hierarchical_type: 'operator_option',
              label: 'asFloat',
              output_type: 'bytes',
            },
          },
        ],
        url: 'https://blockchain.info/ticker',
      },
      {
        script: [
          {
            hierarchical_type: 'operator',
            markup_type: 'select',
            options: [
              {
                hierarchical_type: 'operator_option',
                label: 'asArray',
                markup: 'option',
                output_type: 'Array',
              },
              {
                hierarchical_type: 'operator_option',
                label: 'asBoolean',
                markup: 'option',
                output_type: 'Boolean',
              },
              {
                hierarchical_type: 'operator_option',
                label: 'asFloat',
                markup: 'option',
                output_type: 'Float',
              },
              {
                hierarchical_type: 'operator_option',
                label: 'asInteger',
                markup: 'option',
                output_type: 'Integer',
              },
              {
                hierarchical_type: 'operator_option',
                label: 'asMap',
                markup: 'option',
                output_type: 'Map',
              },
              {
                hierarchical_type: 'operator_option',
                label: 'asString',
                markup: 'option',
                output_type: 'String',
              },
              {
                hierarchical_type: 'operator_option',
                label: 'hash',
                markup: 'option',
                output_type: 'Bytes',
              },
            ],
            output_type: ['String'],
            selected: {
              arguments: [],
              hierarchical_type: 'operator_option',
              label: 'asString',
              output_type: 'bytes',
            },
          },
          {
            hierarchical_type: 'operator',
            markup_type: 'select',
            options: [
              {
                hierarchical_type: 'operator_option',
                label: 'asBytes',
                markup: 'option',
                output_type: 'Bytes',
              },
              {
                hierarchical_type: 'operator_option',
                label: 'asFloat',
                markup: 'option',
                output_type: 'Float',
              },
              {
                hierarchical_type: 'operator_option',
                label: 'asInteger',
                markup: 'option',
                output_type: 'Integer',
              },
              {
                hierarchical_type: 'operator_option',
                label: 'length',
                markup: 'option',
                output_type: 'Integer',
              },
              {
                hierarchical_type: 'operator_option',
                label: 'match',
                markup: 'option',
                output_type: 'Argument',
              },
              {
                hierarchical_type: 'operator_option',
                label: 'parseJSON',
                markup: 'option',
                output_type: 'Bytes',
              },
              {
                hierarchical_type: 'operator_option',
                label: 'parseXML',
                markup: 'option',
                output_type: 'Map',
              },
              {
                hierarchical_type: 'operator_option',
                label: 'asBoolean',
                markup: 'option',
                output_type: 'Boolean',
              },
              {
                hierarchical_type: 'operator_option',
                label: 'toLowerCase',
                markup: 'option',
                output_type: 'String',
              },
              {
                hierarchical_type: 'operator_option',
                label: 'toUpperCase',
                markup: 'option',
                output_type: 'String',
              },
            ],
            output_type: ['Bytes'],
            selected: {
              arguments: [],
              hierarchical_type: 'operator_option',
              label: 'parseJson',
              output_type: 'bytes',
            },
          },
          {
            hierarchical_type: 'operator',
            markup_type: 'select',
            options: [
              {
                hierarchical_type: 'operator_option',
                label: 'asArray',
                markup: 'option',
                output_type: 'Array',
              },
              {
                hierarchical_type: 'operator_option',
                label: 'asBoolean',
                markup: 'option',
                output_type: 'Boolean',
              },
              {
                hierarchical_type: 'operator_option',
                label: 'asFloat',
                markup: 'option',
                output_type: 'Float',
              },
              {
                hierarchical_type: 'operator_option',
                label: 'asInteger',
                markup: 'option',
                output_type: 'Integer',
              },
              {
                hierarchical_type: 'operator_option',
                label: 'asMap',
                markup: 'option',
                output_type: 'Map',
              },
              {
                hierarchical_type: 'operator_option',
                label: 'asString',
                markup: 'option',
                output_type: 'String',
              },
              {
                hierarchical_type: 'operator_option',
                label: 'hash',
                markup: 'option',
                output_type: 'Bytes',
              },
            ],
            output_type: ['Map', 'Bytes'],
            selected: {
              arguments: [],
              hierarchical_type: 'operator_option',
              label: 'asMap',
              output_type: 'bytes',
            },
          },
          {
            hierarchical_type: 'operator',
            markup_type: 'select',
            options: [
              {
                hierarchical_type: 'operator_option',
                label: 'entries',
                markup: 'option',
                output_type: 'Array',
              },
              {
                hierarchical_type: 'operator_option',
                label: 'get',
                markup: 'option',
                output_type: 'Inner',
              },
              {
                hierarchical_type: 'operator_option',
                label: 'keys',
                markup: 'option',
                output_type: 'String',
              },
              {
                hierarchical_type: 'operator_option',
                label: 'values',
                markup: 'option',
                output_type: 'Inner',
              },
            ],
            output_type: ['Inner'],
            selected: {
              arguments: [
                {
                  hierarchical_type: 'argument',
                  id: 6,
                  label: 'key',
                  markup_type: 'input',
                  value: 'last',
                },
              ],
              hierarchical_type: 'operator_option',
              label: 'get',
              output_type: 'bytes',
            },
          },
          {
            hierarchical_type: 'operator',
            markup_type: 'select',
            options: [
              {
                hierarchical_type: 'operator_option',
                label: 'asArray',
                markup: 'option',
                output_type: 'Array',
              },
              {
                hierarchical_type: 'operator_option',
                label: 'asBoolean',
                markup: 'option',
                output_type: 'Boolean',
              },
              {
                hierarchical_type: 'operator_option',
                label: 'asFloat',
                markup: 'option',
                output_type: 'Float',
              },
              {
                hierarchical_type: 'operator_option',
                label: 'asInteger',
                markup: 'option',
                output_type: 'Integer',
              },
              {
                hierarchical_type: 'operator_option',
                label: 'asMap',
                markup: 'option',
                output_type: 'Map',
              },
              {
                hierarchical_type: 'operator_option',
                label: 'asString',
                markup: 'option',
                output_type: 'String',
              },
              {
                hierarchical_type: 'operator_option',
                label: 'hash',
                markup: 'option',
                output_type: 'Bytes',
              },
            ],
            output_type: ['Float'],
            selected: {
              arguments: [],
              hierarchical_type: 'operator_option',
              label: 'asFloat',
              output_type: 'bytes',
            },
          },
        ],
        url: 'https://www.bitstamp.net/api/ticker/',
      },
    ],
    tally: {
      script: [
        {
          hierarchical_type: 'operator',
          markup_type: 'select',
          options: [
            {
              hierarchical_type: 'operator_option',
              label: 'asBytes',
              markup: 'option',
              output_type: 'Bytes',
            },
            {
              hierarchical_type: 'operator_option',
              label: 'count',
              markup: 'option',
              output_type: 'Integer',
            },
            {
              hierarchical_type: 'operator_option',
              label: 'every',
              markup: 'option',
              output_type: 'Boolean',
            },
            {
              hierarchical_type: 'operator_option',
              label: 'filter',
              markup: 'option',
              output_type: 'Array',
            },
            {
              hierarchical_type: 'operator_option',
              label: 'flatten',
              markup: 'option',
              output_type: 'Array',
            },
            {
              hierarchical_type: 'operator_option',
              label: 'get',
              markup: 'option',
              output_type: 'Inner',
            },
            {
              hierarchical_type: 'operator_option',
              label: 'map',
              markup: 'option',
              output_type: 'Argument',
            },
            {
              hierarchical_type: 'operator_option',
              label: 'reduce',
              markup: 'option',
              output_type: 'Inner',
            },
            {
              hierarchical_type: 'operator_option',
              label: 'some',
              markup: 'option',
              output_type: 'Boolean',
            },
            {
              hierarchical_type: 'operator_option',
              label: 'sort',
              markup: 'option',
              output_type: 'Array',
            },
            {
              hierarchical_type: 'operator_option',
              label: 'take',
              markup: 'option',
              output_type: 'Array',
            },
          ],
          output_type: ['Array', 'Passthrough'],
          selected: {
            arguments: [
              {
                hierarchical_type: 'argument',
                id: 10,
                label: 'depth',
                markup_type: 'input',
                value: undefined,
              },
            ],
            hierarchical_type: 'operator_option',
            label: 'flatten',
            output_type: 'bytes',
          },
        },
        {
          hierarchical_type: 'operator',
          markup_type: 'select',
          options: [
            {
              hierarchical_type: 'operator_option',
              label: 'asBytes',
              markup: 'option',
              output_type: 'Bytes',
            },
            {
              hierarchical_type: 'operator_option',
              label: 'count',
              markup: 'option',
              output_type: 'Integer',
            },
            {
              hierarchical_type: 'operator_option',
              label: 'every',
              markup: 'option',
              output_type: 'Boolean',
            },
            {
              hierarchical_type: 'operator_option',
              label: 'filter',
              markup: 'option',
              output_type: 'Array',
            },
            {
              hierarchical_type: 'operator_option',
              label: 'flatten',
              markup: 'option',
              output_type: 'Array',
            },
            {
              hierarchical_type: 'operator_option',
              label: 'get',
              markup: 'option',
              output_type: 'Inner',
            },
            {
              hierarchical_type: 'operator_option',
              label: 'map',
              markup: 'option',
              output_type: 'Argument',
            },
            {
              hierarchical_type: 'operator_option',
              label: 'reduce',
              markup: 'option',
              output_type: 'Inner',
            },
            {
              hierarchical_type: 'operator_option',
              label: 'some',
              markup: 'option',
              output_type: 'Boolean',
            },
            {
              hierarchical_type: 'operator_option',
              label: 'sort',
              markup: 'option',
              output_type: 'Array',
            },
            {
              hierarchical_type: 'operator_option',
              label: 'take',
              markup: 'option',
              output_type: 'Array',
            },
          ],
          output_type: ['Array', 'Inner'],
          selected: {
            arguments: [
              {
                hierarchical_type: 'argument',
                id: 11,
                label: 'function',
                markup_type: 'input',
                options: [
                  {
                    hierarchical_type: 'argument_option',
                    label: 'greaterThan',
                    markup_type: 'option',
                    meta: {},
                    output_type: 'Bytes',
                  },
                  {
                    hierarchical_type: 'argument_option',
                    label: 'lessThan',
                    markup_type: 'option',
                    meta: {},
                    output_type: 'Bytes',
                  },
                  {
                    hierarchical_type: 'argument_option',
                    label: 'equals',
                    markup_type: 'option',
                    meta: {},
                    output_type: 'Bytes',
                  },
                  {
                    hierarchical_type: 'argument_option',
                    label: 'deviationAbsolute',
                    markup_type: 'option',
                    meta: {},
                    output_type: 'Bytes',
                  },
                  {
                    hierarchical_type: 'argument_option',
                    label: 'deviationRelative',
                    markup_type: 'option',
                    meta: {},
                    output_type: 'Bytes',
                  },
                  {
                    hierarchical_type: 'argument_option',
                    label: 'deviationStandard',
                    markup_type: 'option',
                    meta: {},
                    output_type: 'Bytes',
                  },
                  {
                    hierarchical_type: 'argument_option',
                    label: 'top',
                    markup_type: 'option',
                    meta: {},
                    output_type: 'Bytes',
                  },
                  {
                    hierarchical_type: 'argument_option',
                    label: 'bottom',
                    markup_type: 'option',
                    meta: {},
                    output_type: 'Bytes',
                  },
                  {
                    hierarchical_type: 'argument_option',
                    label: 'lessOrEqualThan',
                    markup_type: 'option',
                    meta: {},
                    output_type: 'Bytes',
                  },
                  {
                    hierarchical_type: 'argument_option',
                    label: 'greaterOrEqualThan',
                    markup_type: 'option',
                    meta: {},
                    output_type: 'Bytes',
                  },
                  {
                    hierarchical_type: 'argument_option',
                    label: 'notEquals',
                    markup_type: 'option',
                    meta: {},
                    output_type: 'Bytes',
                  },
                  {
                    hierarchical_type: 'argument_option',
                    label: 'notDeviationAbsolute',
                    markup_type: 'option',
                    meta: {},
                    output_type: 'Bytes',
                  },
                  {
                    hierarchical_type: 'argument_option',
                    label: 'notDeviationRelative',
                    markup_type: 'option',
                    meta: {},
                    output_type: 'Bytes',
                  },
                  {
                    hierarchical_type: 'argument_option',
                    label: 'notDeviationStandard',
                    markup_type: 'option',
                    meta: {},
                    output_type: 'Bytes',
                  },
                  {
                    hierarchical_type: 'argument_option',
                    label: 'notTop',
                    markup_type: 'option',
                    meta: {},
                    output_type: 'Bytes',
                  },
                  {
                    hierarchical_type: 'argument_option',
                    label: 'notBottom',
                    markup_type: 'option',
                    meta: {},
                    output_type: 'Bytes',
                  },
                ],
                selected: {
                  hierarchical_type: 'operator_option',
                  label: 'deviationStandard',
                  markup_type: 'option',
                  output_type: 'array',
                },
              },
            ],
            hierarchical_type: 'operator_option',
            label: 'filter',
            output_type: 'bytes',
          },
        },
        {
          hierarchical_type: 'operator',
          markup_type: 'select',
          options: [
            {
              hierarchical_type: 'operator_option',
              label: 'asBytes',
              markup: 'option',
              output_type: 'Bytes',
            },
            {
              hierarchical_type: 'operator_option',
              label: 'count',
              markup: 'option',
              output_type: 'Integer',
            },
            {
              hierarchical_type: 'operator_option',
              label: 'every',
              markup: 'option',
              output_type: 'Boolean',
            },
            {
              hierarchical_type: 'operator_option',
              label: 'filter',
              markup: 'option',
              output_type: 'Array',
            },
            {
              hierarchical_type: 'operator_option',
              label: 'flatten',
              markup: 'option',
              output_type: 'Array',
            },
            {
              hierarchical_type: 'operator_option',
              label: 'get',
              markup: 'option',
              output_type: 'Inner',
            },
            {
              hierarchical_type: 'operator_option',
              label: 'map',
              markup: 'option',
              output_type: 'Argument',
            },
            {
              hierarchical_type: 'operator_option',
              label: 'reduce',
              markup: 'option',
              output_type: 'Inner',
            },
            {
              hierarchical_type: 'operator_option',
              label: 'some',
              markup: 'option',
              output_type: 'Boolean',
            },
            {
              hierarchical_type: 'operator_option',
              label: 'sort',
              markup: 'option',
              output_type: 'Array',
            },
            {
              hierarchical_type: 'operator_option',
              label: 'take',
              markup: 'option',
              output_type: 'Array',
            },
          ],
          output_type: ['Inner'],
          selected: {
            arguments: [
              {
                hierarchical_type: 'argument',
                id: 12,
                label: 'function',
                markup_type: 'input',
                options: [
                  {
                    hierarchical_type: 'argument_option',
                    label: 'min',
                    markup_type: 'option',
                    meta: {},
                    output_type: 'integer',
                  },
                  {
                    hierarchical_type: 'argument_option',
                    label: 'max',
                    markup_type: 'option',
                    meta: {},
                    output_type: 'integer',
                  },
                  {
                    hierarchical_type: 'argument_option',
                    label: 'averageMean',
                    markup_type: 'option',
                    meta: {},
                    output_type: 'integer',
                  },
                  {
                    hierarchical_type: 'argument_option',
                    label: 'max',
                    markup_type: 'option',
                    meta: {},
                    output_type: 'integer',
                  },
                  {
                    hierarchical_type: 'argument_option',
                    label: 'averageMean',
                    markup_type: 'option',
                    meta: {},
                    output_type: 'integer',
                  },
                  {
                    hierarchical_type: 'argument_option',
                    label: 'averageMeanWeighted',
                    markup_type: 'option',
                    meta: {},
                    output_type: 'integer',
                  },
                  {
                    hierarchical_type: 'argument_option',
                    label: 'averageMedian',
                    markup_type: 'option',
                    meta: {},
                    output_type: 'integer',
                  },
                  {
                    hierarchical_type: 'argument_option',
                    label: 'averageMedianWeighted',
                    markup_type: 'option',
                    meta: {},
                    output_type: 'integer',
                  },
                  {
                    hierarchical_type: 'argument_option',
                    label: 'deviationStandard',
                    markup_type: 'option',
                    meta: {},
                    output_type: 'integer',
                  },
                  {
                    hierarchical_type: 'argument_option',
                    label: 'deviationAverage',
                    markup_type: 'option',
                    meta: {},
                    output_type: 'integer',
                  },
                  {
                    hierarchical_type: 'argument_option',
                    label: 'deviationMedian',
                    markup_type: 'option',
                    meta: {},
                    output_type: 'integer',
                  },
                  {
                    hierarchical_type: 'argument_option',
                    label: 'deviationMaximum',
                    markup_type: 'option',
                    meta: {},
                    output_type: 'integer',
                  },
                ],
                selected: {
                  hierarchical_type: 'operator_option',
                  label: 'averageMean',
                  markup_type: 'option',
                  output_type: 'array',
                },
              },
            ],
            hierarchical_type: 'operator_option',
            label: 'reduce',
            output_type: 'bytes',
          },
        },
      ],
    },
  },
}
